# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-13 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('name', models.CharField(max_length=1000)),
                ('message', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=500)),
            ],
        ),
    ]
